stages:
  - build
  - security

# --- Build internal SDK first ---
build_or_sdk:
  stage: build
  image: gradle:8.8-jdk21
  variables:
    ANDROID_SDK_ROOT: "/opt/android-sdk"
  before_script:
    - apt-get update && apt-get install -y wget unzip
    - wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdtools.zip
    - mkdir -p ${ANDROID_SDK_ROOT}/cmdline-tools
    - unzip -q cmdtools.zip -d ${ANDROID_SDK_ROOT}/cmdline-tools
    - mv ${ANDROID_SDK_ROOT}/cmdline-tools/cmdline-tools ${ANDROID_SDK_ROOT}/cmdline-tools/latest
    - yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platform-tools" "platforms;android-34" "build-tools;34.0.0"
    - chmod +x gradlew
  script:
    - cd android
    - ./gradlew :or-sdk:assembleRelease
  artifacts:
    paths:
      - android/or-sdk/build
    expire_in: 1h


# --- Security scanning (includes both GitLab templates) ---
include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

dependency_scanning:
  stage: security
  needs: ["build_or_sdk"]
  variables:
    DS_JAVA_VERSION: "21"

secret_detection:
  stage: security
