include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  
variables:
  MAVEN_REPO_URL: "https://git.tetrapi.pt/api/v4/projects/208/packages/maven"
  MAVEN_REPO_TOKEN: $CI_JOB_TOKEN
